services:
  - type: web
    name: digital-nomad-express
    env: static
    buildCommand: echo "Static site - no build required"
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 